### PR TITLE
es.json

### PR DESCRIPTION
**Pull request by Cristofer07**
Spanish translation

### CODE REVIEW

**Comment by Molenfeuer** [comment]
Wow! Thx :D I'll merge it tomorrow!

**Comment by Molenfeuer** [comment]
Should I link to your GitHub account for the credits? Or did you prefere your NexusMods acc? Send me your Nexus account in case!

**Comment by Cristofer07** [comment]
> Should I link to your GitHub account for the credits? Or did you prefere your NexusMods acc? Send me your Nexus account in case!

as you like, just in case this is my nexus user "Cris0007"

**Comment by Molenfeuer** [comment]
Thx :3 Kind regards from Germany!

**Pull request merged**
